[package]
name = "pfd"
version = "0.1.0"
edition = "2024"

[dependencies]
discovery = { path = "../discovery" }
tokio = { version = "1", features = ["net", "signal", "macros", "rt", "io-util"] }
tracing = "0.1"
anyhow = "1"
sendfd = { version = "0.4", features = ["tokio"] }
