[package]
name = "discovery"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Unix domain socket discovery strategies"

[dependencies]
anyhow.workspace = true
tracing.workspace = true
